[package]
name = "application"
version = "0.1.0"
edition = "2024"

[dependencies]
core_hal = { path = "../core_hal" }
winit = { path = "../backend/window/winit", optional = true }
wgpu = { path = "../backend/renderer/wgpu", optional = true }

[features]
default = ["winit", "wgpu"]

